### PR TITLE
Update singularity cannon

### PR DESCRIPTION
**Pull request by feilaosi**
in progress.

### CODE REVIEW

**Comment by feilaosi** [comment]
not sure about MAG technology, maybe this should be in the wiki.

**Comment by cloudwu** [comment]
MAG 应该指机关枪，有时也叫机枪。 就是那种可以连续发射子弹的武器。

**Comment by feilaosi** [comment]
Hmm, found it here in http://xenonauts.wikia.com/wiki/Tech_Trees
Maybe it is included in "Research.MAGWeaponry"

Alien Kinetic Shield
        |
        |
   MAG Weaponry
        |
        |
 Heavy MAG Weaponry

**Comment by cloudwu** [comment]
对。这种游戏自造的词都先留着吧

**Pull request merged**
